import { montserrat } from './ui/fonts';
import { usePathname } from 'next/navigation';
// Locales
// import es from '../../public/locale/es';
// import en from '../../public/locale/en';
// const pathname = usePathname();
// const { locale } = router;
// const t = locale === 'es' ? es : en;

import "./globals.css"
import Navbar from './ui/components/Navbar';

import { connectDB } from './lib/db-connect'
// await connectDB()
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({ children }) {
  

  
  return (
    <html lang="en">

      <body className={`
      ${montserrat.className}
      antialiased 
      bg-neutral-850
      w-full
      flex flex-col items-center justify-between`}>
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
